-- Catalog -------------------------------------------------------------------

create table products (
    id             bigint generated always as identity primary key,
    slug           text not null unique,
    sku            text not null unique,
    name           text not null,
    kind           text not null check (kind in ('single', 'stack')),
    short_spec     text not null default '',
    description    text not null default '',
    price          numeric(12, 2) not null check (price >= 0),
    image_url      text,
    -- Stock is tracked on single products; a stack is available when all its components are.
    stock_quantity integer not null default 0 check (stock_quantity >= 0),
    is_active      boolean not null default true,
    is_featured    boolean not null default false,
    is_new         boolean not null default false,
    sort_order     integer not null default 0,
    created_at     timestamptz not null default now(),
    updated_at     timestamptz not null default now()
);

create table stack_items (
    stack_product_id     bigint not null references products (id) on delete cascade,
    component_product_id bigint not null references products (id),
    quantity             integer not null default 1 check (quantity > 0),
    primary key (stack_product_id, component_product_id),
    check (stack_product_id <> component_product_id)
);

-- Customers -----------------------------------------------------------------

create table customers (
    id            bigint generated always as identity primary key,
    email         text not null,
    -- Null for guests who checked out without creating an account.
    password_hash text,
    full_name     text not null default '',
    created_at    timestamptz not null default now()
);

create unique index customers_email_key on customers (lower(email));

create table addresses (
    id          bigint generated always as identity primary key,
    customer_id bigint not null references customers (id) on delete cascade,
    full_name   text not null,
    line1       text not null,
    line2       text not null default '',
    city        text not null,
    region      text not null,
    postal_code text not null,
    country     char(2) not null default 'US',
    phone       text not null default '',
    created_at  timestamptz not null default now()
);

create index addresses_customer_id_idx on addresses (customer_id);

-- Carts ---------------------------------------------------------------------

create table carts (
    -- The id is the token stored in the visitor's cookie.
    id          uuid primary key default gen_random_uuid(),
    customer_id bigint references customers (id) on delete set null,
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now()
);

create table cart_items (
    id             bigint generated always as identity primary key,
    cart_id        uuid not null references carts (id) on delete cascade,
    product_id     bigint not null references products (id),
    purchase_mode  text not null check (purchase_mode in ('once', 'subscription')),
    frequency_days integer check (frequency_days in (30, 60, 90)),
    quantity       integer not null check (quantity > 0),
    check ((purchase_mode = 'subscription') = (frequency_days is not null)),
    unique nulls not distinct (cart_id, product_id, purchase_mode, frequency_days)
);

-- Orders and subscriptions --------------------------------------------------

create table orders (
    id                   bigint generated always as identity primary key,
    order_number         text not null unique,
    customer_id          bigint not null references customers (id),
    email                text not null,
    status               text not null default 'pending'
                         check (status in ('pending', 'paid', 'fulfilled', 'cancelled', 'refunded')),
    -- Shipping address is copied onto the order so later address edits don't rewrite history.
    ship_full_name       text not null,
    ship_line1           text not null,
    ship_line2           text not null default '',
    ship_city            text not null,
    ship_region          text not null,
    ship_postal_code     text not null,
    ship_country         char(2) not null,
    subtotal             numeric(12, 2) not null,
    shipping_total       numeric(12, 2) not null default 0,
    tax_total            numeric(12, 2) not null default 0,
    total                numeric(12, 2) not null,
    currency             char(3) not null default 'USD',
    payment_provider     text,
    payment_reference    text,
    -- Set on renewal orders generated by a subscription; null on orders placed at checkout.
    subscription_id      bigint,
    placed_at            timestamptz,
    created_at           timestamptz not null default now()
);

create index orders_customer_id_idx on orders (customer_id);

create table order_items (
    id             bigint generated always as identity primary key,
    order_id       bigint not null references orders (id) on delete cascade,
    product_id     bigint not null references products (id),
    -- Name and price are copied at purchase time.
    product_name   text not null,
    purchase_mode  text not null check (purchase_mode in ('once', 'subscription')),
    frequency_days integer check (frequency_days in (30, 60, 90)),
    quantity       integer not null check (quantity > 0),
    unit_price     numeric(12, 2) not null,
    line_total     numeric(12, 2) not null
);

create index order_items_order_id_idx on order_items (order_id);

-- One subscription per delivery frequency in the originating order.
create table subscriptions (
    id                       bigint generated always as identity primary key,
    customer_id              bigint not null references customers (id),
    origin_order_id          bigint not null references orders (id),
    shipping_address_id      bigint not null references addresses (id),
    status                   text not null default 'active'
                             check (status in ('active', 'paused', 'cancelled')),
    frequency_days           integer not null check (frequency_days in (30, 60, 90)),
    next_charge_on           date,
    payment_provider         text,
    payment_method_reference text,
    created_at               timestamptz not null default now(),
    cancelled_at             timestamptz
);

create index subscriptions_customer_id_idx on subscriptions (customer_id);
create index subscriptions_due_idx on subscriptions (next_charge_on) where status = 'active';

create table subscription_items (
    subscription_id bigint not null references subscriptions (id) on delete cascade,
    product_id      bigint not null references products (id),
    quantity        integer not null check (quantity > 0),
    unit_price      numeric(12, 2) not null,
    primary key (subscription_id, product_id)
);

alter table orders
    add constraint orders_subscription_id_fkey foreign key (subscription_id) references subscriptions (id);
